### YamlMime:Landing
title: Kubernetes habilitado para Azure Arc
summary: Aprenda a administrar clústeres de Kubernetes con Azure Arc
metadata:
  title: Kubernetes habilitado para Azure Arc
  description: Más información sobre cómo administrar máquinas locales en Azure
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 03/02/2021
  ms.author: shasb
  ms.openlocfilehash: fbad5cafb22960a56a4ba76e2dc331c399193ddc
  ms.sourcegitcommit: 56b0c7923d67f96da21653b4bb37d943c36a81d6
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 04/06/2021
  ms.locfileid: "106443210"
landingContent:
- title: Acerca de Kubernetes habilitado para Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: ¿Qué es Kubernetes habilitado para Azure Arc?
      url: overview.md
    - text: Programa de validación de Azure Arc
      url: validation-program.md
  - linkListType: concept
    links:
    - text: Arquitectura de agente
      url: conceptual-agent-architecture.md
    - text: Configuraciones y GitOps
      url: conceptual-configurations.md
    - text: Flujo de trabajo de CI/CD mediante GitOps
      url: conceptual-gitops-ci-cd.md
    - text: Preguntas más frecuentes
      url: faq.md
- title: Introducción
  linkLists:
  - linkListType: quickstart
    links:
    - text: Conexión de un clúster a Azure Arc
      url: quickstart-connect-cluster.md
- title: Implementación de configuraciones mediante GitOps
  linkLists:
  - linkListType: tutorial
    links:
    - text: Implementación de configuraciones mediante GitOps
      url: tutorial-use-gitops-connected-cluster.md
    - text: Implementación de CI/CD con GitOps
      url: tutorial-gitops-ci-cd.md
- title: Configuración, gobierno y supervisión de clústeres
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Implementación de gráficos de Helm mediante GitOps
      url: use-gitops-with-helm.md
    - text: Aplicación de GitOps mediante Azure Policy
      url: use-azure-policy.md
    - text: Implementación de extensiones en clústeres
      url: extensions.md
    - text: Implementación de cargas de trabajo de Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Prueba de concepto
  linkLists:
  - linkListType: sample
    links:
    - text: Jumpstart
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Arquitectura de referencia
  linkLists:
  - linkListType: architecture
    links:
    - text: Administración de implementaciones y configuraciones para clústeres híbridos de Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
