- name: Kubernetes habilitado para Azure Arc
  href: index.yml
- name: Información general
  items:
    - name: Acerca de Kubernetes habilitado para Azure Arc
      href: overview.md
    - name: Programa de validación de Azure Arc
      href: validation-program.md
- name: Guías de inicio rápido
  items:
    - name: Conexión de un clúster a Azure Arc
      href: quickstart-connect-cluster.md
- name: Tutoriales
  items:
    - name: Implementación de configuraciones mediante GitOps
      href: tutorial-use-gitops-connected-cluster.md
    - name: Implementación de CI/CD con GitOps
      href: tutorial-gitops-ci-cd.md
- name: Conceptos
  items:
    - name: Arquitectura de agente
      href: conceptual-agent-architecture.md
    - name: Configuraciones y GitOps
      href: conceptual-configurations.md
    - name: Extensiones de clúster
      href: conceptual-extensions.md
    - name: Conexión de clúster
      href: conceptual-cluster-connect.md
    - name: Ubicaciones personalizadas
      href: conceptual-custom-locations.md
    - name: Azure RBAC
      href: conceptual-azure-rbac.md
    - name: Preguntas más frecuentes
      href: faq.md
    - name: Flujo de trabajo de CI/CD mediante GitOps
      href: conceptual-gitops-ci-cd.md
- name: Guías paso a paso
  items:
    - name: Conexión del clúster mediante una entidad de servicio
      href: create-onboarding-service-principal.md
    - name: Actualización de agentes
      href: agent-upgrade.md
    - name: Escenarios
      items:
        - name: Implementación de gráficos de Helm mediante GitOps
          href: use-gitops-with-helm.md
        - name: Aplicación de GitOps mediante Azure Policy
          href: use-azure-policy.md
        - name: Implementación y administración de extensiones de clúster
          href: extensions.md
        - name: Supervisión mediante Azure Monitor para contenedores
          href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Aplicación de la protección contra amenazas con Azure Defender
          href: ../../security-center/defender-for-kubernetes-azure-arc.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Directivas de control de admisión mediante Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Conexión segura a un clúster desde cualquier lugar
          href: cluster-connect.md
        - name: "Uso del control de acceso basado en roles de Azure\_AD para comprobaciones de autorización"
          href: azure-rbac.md
        - name: Creación de ubicaciones personalizadas
          href: custom-locations.md
        - name: Implementación de cargas de trabajo de IoT
          href: deploy-azure-iot-edge-workloads.md
    - name: Solución de problemas
      href: Troubleshooting.md
- name: Referencia
  items:
    - name: Elementos integrados de Azure Policy
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Recursos
  items:
    - name: Azure Arc Jumpstart
      href: 'https://azurearcjumpstart.io'